linters:
  enable-all: true

linters-settings:
  gofumpt:
    module-path: dockercolorize
  varnamelen:
    ignore-names: [i, in, j, m, sb, tt, v]
  wrapcheck:
    ignorePackageGlobs: [dockercolorize/internal/*]
