linters:
  enable-all: true

linters-settings:
  gofumpt:
    module-path: docker-color-output
  varnamelen:
    ignore-names: [ i, in, j, m, sb, tt, v ]
  wrapcheck:
    ignorePackageGlobs: [ docker-color-output/internal/* ]
