project_name: dockercolorize

builds:
  - id: doclercolorize
    main: ./cmd/cli/
    goos:
      - darwin
      - linux

brews:
  - tap:
      owner: PunGrumpy
      name: homebrew-formulas
    folder: formula
    homepage: https://github.com/PunGrumpy/dockercolorize
    description: A simple tool to colorize docker output
    commit_author:
      name: PunGrumpy
      email: 108584943+PunGrumpy@users.noreply.github.com
