name: Release

on:
  workflow_run:
    workflows: ['Go']
    types: [completed]
  push:
    tags:
      - 'v*'

jobs:
  publish_homebrew:
    name: Publish Homebrew
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Get Version
        id: get-version
        run: |
          VER_FILE=.version
          VER=$(cat $VER_FILE)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Go Releaser
        if: ${{ env.VERSION }} != '' && github.tag != ''
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
