name: Release

on:
  workflow_run:
    workflows:
      - Go
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: |
          file_path="internal/app/const.go"
          echo VERSION=$(grep -oP '(?<=Ver\s=\s")[^"]+' "$file_path") >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
          tag_name: ${{ env.VERSION }}
          body: |
            ## 🔔 ${{ github.event.workflow_run.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
